"""
CLI for the review-to-fix batch triage workflow (spec-review-to-fix).

This script does NOT investigate feedback itself. The agent (Claude Code) or the
dev investigates each feedback row (reads code, runs reproduce/tests) and then
uses this script only to record the outcome and manage state:

    list-pending    -- show Feedback rows not yet assigned to a batch
    assign-batch    -- record an investigated batch's diagnosis (root cause,
                       confidence, proposed fix, impact) and tag the feedback rows
    set-status      -- dev approves/dismisses a batch
    generate-spec   -- turn an approved batch into a plain intent-<slug>.md brief,
                       ready to be ingested as fresh raw intent by bmad-quick-dev

Core logic lives in plain functions (list_pending / assign_batch / set_status /
generate_spec) so tests can call them directly without subprocessing the CLI.
The `if __name__ == "__main__"` block below is a thin argparse wrapper around them.
"""
import argparse
import os
import re
import sys
from pathlib import Path

# Make project root importable when run as a script (`python3 tools/feedback_triage.py ...`)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from sqlalchemy.orm import Session

from db.models import Feedback

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS_DIR = PROJECT_ROOT / "_bmad-output" / "implementation-artifacts"
TRIAGE_MD_PATH = ARTIFACTS_DIR / "feedback-triage.md"

VALID_CONFIDENCE = {"confirmed", "unverified"}
VALID_STATUS = {"pending", "approved", "dismissed"}

# Batch slugs become part of a file path (intent-<slug>.md) and get interpolated
# into feedback-triage.md, so they're restricted to a safe, unambiguous charset:
# no path separators / "..", no quote chars, no case-collisions on case-insensitive
# filesystems.
BATCH_SLUG_RE = re.compile(r"^[a-z0-9-]+$")

# Prefixes that would be misread as section/field boundaries by the line-based
# feedback-triage.md parser if they showed up verbatim inside a free-text field.
_MARKDOWN_MARKER_PREFIXES = ("## ", "- ")

TRIAGE_MD_HEADER = (
    "# Feedback Triage Batches\n\n"
    "<!-- Generated by tools/feedback_triage.py. Each `## Batch: <slug>` section is\n"
    "     one investigated, grouped root cause. `set-status` updates the `Status:`\n"
    "     line in place; `generate-spec` reads a section back out once approved. -->\n"
)


# ── list-pending ──────────────────────────────────────────────────

def list_pending(db: Session):
    """Return all Feedback rows not yet assigned to a triage batch, oldest first."""
    return (
        db.query(Feedback)
        .filter(Feedback.triage_batch.is_(None))
        .order_by(Feedback.id)
        .all()
    )


# ── validation helpers ────────────────────────────────────────────

def _validate_batch_slug(batch_slug: str):
    if not batch_slug or not BATCH_SLUG_RE.match(batch_slug):
        raise ValueError(
            f"--batch slug must match ^[a-z0-9-]+$ (lowercase letters, digits, "
            f"hyphens only — no '/', '..', quotes, or uppercase), got {batch_slug!r}"
        )


def _validate_no_injection(field_name: str, value: str):
    """
    Reject values that would corrupt feedback-triage.md's line-based section
    parser: newlines (which could forge extra `- Key: value` lines or a new
    `## Batch:` header), and single-line values that themselves look like a
    section/field marker.
    """
    if "\n" in value or "\r" in value:
        raise ValueError(
            f"--{field_name} must not contain newline characters (would corrupt "
            f"feedback-triage.md's section parsing), got {value!r}"
        )
    if value.startswith(_MARKDOWN_MARKER_PREFIXES):
        raise ValueError(
            f"--{field_name} must not start with {_MARKDOWN_MARKER_PREFIXES!r} "
            f"(would be misread as a markdown section/field marker), got {value!r}"
        )


# ── feedback-triage.md parsing helpers ───────────────────────────

def _section_bounds(content: str, slug: str):
    """Return (start, end) char offsets of the `## Batch: <slug>` section, or None."""
    header_re = re.compile(r"^## Batch: (.+)$", re.MULTILINE)
    headers = list(header_re.finditer(content))
    for i, m in enumerate(headers):
        if m.group(1).strip() == slug:
            start = m.start()
            end = headers[i + 1].start() if i + 1 < len(headers) else len(content)
            return start, end
    return None


def _parse_batch_fields(content: str, slug: str):
    """Parse a batch section's `- Key: value` lines into a dict, or None if not found."""
    bounds = _section_bounds(content, slug)
    if bounds is None:
        return None
    section = content[bounds[0]:bounds[1]]
    fields = {}
    for line in section.splitlines():
        line = line.strip()
        if line.startswith("- "):
            key, _, val = line[2:].partition(":")
            fields[key.strip()] = val.strip()
    return fields


def _render_batch_section(ids, batch_slug, root_cause, confidence, proposed_fix, impact, status="pending"):
    ids_str = ", ".join(str(i) for i in ids)
    return (
        f"\n## Batch: {batch_slug}\n"
        f"- Feedback IDs: {ids_str}\n"
        f"- Root cause: {root_cause}\n"
        f"- Confidence: {confidence}\n"
        f"- Proposed fix: {proposed_fix}\n"
        f"- Impact: {impact}\n"
        f"- Status: {status}\n"
    )


def _set_batch_status_in_content(content: str, slug: str, new_status: str) -> str:
    bounds = _section_bounds(content, slug)
    if bounds is None:
        raise ValueError(f"Batch '{slug}' not found in {TRIAGE_MD_PATH.name}")
    start, end = bounds
    section = content[start:end]
    new_section, n = re.subn(r"(?m)^- Status:.*$", f"- Status: {new_status}", section)
    if n == 0:
        new_section = section.rstrip("\n") + f"\n- Status: {new_status}\n"
    return content[:start] + new_section + content[end:]


# ── assign-batch ──────────────────────────────────────────────────

def assign_batch(
    db: Session,
    ids,
    batch_slug: str,
    root_cause: str,
    confidence: str,
    proposed_fix: str,
    impact: str,
    triage_md_path: Path = TRIAGE_MD_PATH,
):
    """
    Validate everything, then tag those Feedback rows with `batch_slug` /
    triage_status="pending" and append one section to feedback-triage.md.

    Raises ValueError (no DB writes, no file writes) if, before any mutation:
      - confidence is not "confirmed" or "unverified"
      - ids is empty
      - batch_slug does not match ^[a-z0-9-]+$
      - root_cause / proposed_fix / impact contains a newline, or a line that
        looks like a markdown section/field marker ("## " / "- " prefix)
      - any id in `ids` does not exist in the Feedback table
      - any id in `ids` already has a non-null triage_batch belonging to a
        *different* batch (would silently re-tag / orphan it)
      - batch_slug already has a section in feedback-triage.md (duplicate batch)

    Once validation passes, the markdown file is written BEFORE the DB commit;
    if the file write raises, the DB transaction is rolled back so the two
    never drift out of sync.
    """
    if confidence not in VALID_CONFIDENCE:
        raise ValueError(
            f"confidence must be one of {sorted(VALID_CONFIDENCE)}, got '{confidence}'"
        )
    if not ids:
        raise ValueError("ids must be a non-empty list")

    _validate_batch_slug(batch_slug)
    _validate_no_injection("root-cause", root_cause)
    _validate_no_injection("proposed-fix", proposed_fix)
    _validate_no_injection("impact", impact)

    ids = [int(i) for i in ids]
    dedup_ids = list(dict.fromkeys(ids))  # de-dupe, preserve first-seen order

    rows = db.query(Feedback).filter(Feedback.id.in_(dedup_ids)).all()
    rows_by_id = {row.id: row for row in rows}
    missing = sorted(set(dedup_ids) - set(rows_by_id))
    if missing:
        raise ValueError(f"Feedback id(s) not found, aborting with no changes: {missing}")

    already_claimed = {
        fid: row.triage_batch
        for fid, row in rows_by_id.items()
        if row.triage_batch is not None and row.triage_batch != batch_slug
    }
    if already_claimed:
        detail = ", ".join(f"{fid} (batch '{b}')" for fid, b in sorted(already_claimed.items()))
        raise ValueError(
            f"Feedback id(s) already assigned to a different batch, aborting with no changes: {detail}"
        )

    triage_md_path.parent.mkdir(parents=True, exist_ok=True)
    if triage_md_path.exists():
        existing = triage_md_path.read_text(encoding="utf-8")
    else:
        existing = TRIAGE_MD_HEADER

    if _section_bounds(existing, batch_slug) is not None:
        raise ValueError(
            f"Batch '{batch_slug}' already has a section in {triage_md_path.name}; "
            "pick a different --batch slug (this one is already in use)"
        )

    section = _render_batch_section(dedup_ids, batch_slug, root_cause, confidence, proposed_fix, impact)
    new_content = existing.rstrip("\n") + "\n" + section

    # Stage the DB mutation in-session, but don't commit until the file write
    # (which can legitimately fail: permissions, disk full) has succeeded.
    for row in rows_by_id.values():
        row.triage_batch = batch_slug
        row.triage_status = "pending"

    try:
        triage_md_path.write_text(new_content, encoding="utf-8")
    except OSError:
        db.rollback()
        raise

    db.commit()

    return [rows_by_id[i] for i in dedup_ids]


# ── set-status ────────────────────────────────────────────────────

def set_status(db: Session, batch_slug: str, status: str, triage_md_path: Path = TRIAGE_MD_PATH):
    """
    Update triage_status for every Feedback row in `batch_slug`, and update the
    `Status:` line of the matching section in feedback-triage.md in place.

    Raises ValueError (no DB writes, no file writes) if:
      - status is not one of pending/approved/dismissed
      - feedback-triage.md does not exist, or has no section for this slug
      - no Feedback rows are tagged with this batch_slug

    The markdown file is written BEFORE the DB commit; if the file write raises,
    the DB transaction is rolled back so the two never drift out of sync.
    """
    if status not in VALID_STATUS:
        raise ValueError(f"status must be one of {sorted(VALID_STATUS)}, got '{status}'")

    if not triage_md_path.exists():
        raise ValueError(f"{triage_md_path} does not exist")
    content = triage_md_path.read_text(encoding="utf-8")
    new_content = _set_batch_status_in_content(content, batch_slug, status)  # raises if section missing

    rows = db.query(Feedback).filter(Feedback.triage_batch == batch_slug).all()
    if not rows:
        raise ValueError(f"No Feedback rows found for batch '{batch_slug}'")

    for row in rows:
        row.triage_status = status

    try:
        triage_md_path.write_text(new_content, encoding="utf-8")
    except OSError:
        db.rollback()
        raise

    db.commit()
    return rows


# ── generate-spec ─────────────────────────────────────────────────

def _render_intent_brief(batch_slug: str, root_cause: str, proposed_fix: str, impact: str) -> str:
    """
    Plain-prose intent brief: no YAML frontmatter, no <frozen-after-approval>
    wrapper, no spec-template.md placeholder tokens. Deliberately minimal so
    bmad-quick-dev's step-01 intent-check (which looks for recognized `status:`
    frontmatter to decide whether to resume a draft) sees no frontmatter here
    and treats this as fresh raw intent to ingest, running a real step-02
    planning pass instead of resuming fake placeholder content.
    """
    return (
        f"# {batch_slug}\n"
        f"\n"
        f"## Problem\n"
        f"\n"
        f"{root_cause}\n"
        f"\n"
        f"## Approach\n"
        f"\n"
        f"{proposed_fix}\n"
        f"\n"
        f"Impact: {impact}\n"
    )


def generate_spec(
    batch_slug: str,
    triage_md_path: Path = TRIAGE_MD_PATH,
    artifacts_dir: Path = ARTIFACTS_DIR,
) -> Path:
    """
    Turn an approved batch into a plain intent brief at intent-<batch_slug>.md,
    ready for a human to run bmad-quick-dev against as fresh raw intent.

    Raises ValueError (no file created) if:
      - feedback-triage.md does not exist, or has no section for this slug
      - the batch's Status is not "approved"
    Raises FileExistsError (no overwrite) if intent-<batch_slug>.md already
    exists. Uses an atomic exclusive-create (open mode "x") rather than an
    exists()-then-write check, so a concurrent call can't race between the
    check and the write and silently clobber an existing brief.
    """
    if not triage_md_path.exists():
        raise ValueError(f"{triage_md_path} does not exist")
    content = triage_md_path.read_text(encoding="utf-8")
    fields = _parse_batch_fields(content, batch_slug)
    if fields is None:
        raise ValueError(f"Batch '{batch_slug}' not found in {triage_md_path.name}")

    status = fields.get("Status", "").strip()
    if status != "approved":
        raise ValueError(
            f"Batch '{batch_slug}' is not approved (current status: '{status}'); refusing to generate spec"
        )

    intent_path = artifacts_dir / f"intent-{batch_slug}.md"

    root_cause = fields.get("Root cause", "")
    proposed_fix = fields.get("Proposed fix", "")
    impact = fields.get("Impact", "")
    content_out = _render_intent_brief(batch_slug, root_cause, proposed_fix, impact)

    artifacts_dir.mkdir(parents=True, exist_ok=True)
    try:
        with open(intent_path, "x", encoding="utf-8") as f:
            f.write(content_out)
    except FileExistsError:
        raise FileExistsError(
            f"{intent_path} already exists; refusing to overwrite — choose a different --batch slug"
        )
    return intent_path


# ── CLI ───────────────────────────────────────────────────────────

def _print_pending(rows):
    if not rows:
        print("No feedback pending triage.")
        return
    for row in rows:
        print(
            f"[{row.id}] screen={row.screen} application_id={row.application_id} "
            f"session_id={row.session_id} message={row.message!r}"
        )


def _parse_ids_csv(raw: str):
    """
    Parse a comma-separated --ids CLI argument (e.g. "12,13,15") into a list of
    ints, raising a ValueError that names the specific malformed token instead
    of letting a raw `invalid literal for int()` bubble up.
    """
    ids = []
    for token in raw.split(","):
        token = token.strip()
        if token == "":
            continue
        try:
            ids.append(int(token))
        except ValueError:
            raise ValueError(f"--ids contains a non-integer token: {token!r} (in --ids={raw!r})")
    return ids


def _cmd_list_pending(args, db):
    _print_pending(list_pending(db))


def _cmd_assign_batch(args, db):
    ids = _parse_ids_csv(args.ids)
    assign_batch(
        db,
        ids=ids,
        batch_slug=args.batch,
        root_cause=args.root_cause,
        confidence=args.confidence,
        proposed_fix=args.proposed_fix,
        impact=args.impact,
    )
    print(f"Batch '{args.batch}' assigned to feedback id(s): {ids}")


def _cmd_set_status(args, db):
    rows = set_status(db, batch_slug=args.batch, status=args.status)
    print(f"Batch '{args.batch}' set to status '{args.status}' ({len(rows)} feedback row(s))")


def _cmd_generate_spec(args, db):
    intent_path = generate_spec(batch_slug=args.batch)
    print(f"Wrote {intent_path}")


def _build_parser():
    parser = argparse.ArgumentParser(description="Feedback review-to-fix triage CLI")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("list-pending", help="List Feedback rows not yet assigned to a batch")

    p_assign = sub.add_parser("assign-batch", help="Record an investigated batch's diagnosis")
    p_assign.add_argument("--ids", required=True, help="Comma-separated Feedback ids, e.g. 12,13,15")
    p_assign.add_argument("--batch", required=True, help="Batch slug")
    p_assign.add_argument("--root-cause", required=True, dest="root_cause")
    p_assign.add_argument("--confidence", required=True, choices=sorted(VALID_CONFIDENCE))
    p_assign.add_argument("--proposed-fix", required=True, dest="proposed_fix")
    p_assign.add_argument("--impact", required=True)

    p_status = sub.add_parser("set-status", help="Dev approves/dismisses a batch")
    p_status.add_argument("--batch", required=True)
    p_status.add_argument("--status", required=True, choices=sorted(VALID_STATUS))

    p_gen = sub.add_parser("generate-spec", help="Generate an intent brief from an approved batch")
    p_gen.add_argument("--batch", required=True)

    return parser


if __name__ == "__main__":
    from db.session import SessionLocal, init_db

    parser = _build_parser()
    args = parser.parse_args()

    # Standalone script — don't require the FastAPI app to have run first.
    init_db()
    db = SessionLocal()
    try:
        handlers = {
            "list-pending": _cmd_list_pending,
            "assign-batch": _cmd_assign_batch,
            "set-status": _cmd_set_status,
            "generate-spec": _cmd_generate_spec,
        }
        handlers[args.command](args, db)
    except (ValueError, FileExistsError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        db.close()
